# Generated by Django 4.1.4 on 2023-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('departamento', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=70)),
                ('sueldo', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
